CREATE TABLE IF NOT EXISTS forms (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    motivo VARCHAR(100) NOT NULL,
    setor VARCHAR(50) NOT NULL,
    problema VARCHAR(100) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_exclusao TIMESTAMP DEFAULT NULL,
    status VARCHAR(20) NOT NULL,
    mensagem VARCHAR(255) NOT NULL DEFAULT,
);